### ISSUE TITLE
columnWidth is always 44

### ISSUE THREAD

**Issue by tgarm** [BurrowsWang/BWHorizontalTableView#1]
The BWHorizontalTableView.columnWidth is always the default value.

I tried add 
            self.columnWidth = columnWidth;
after BWHorizontalTavleView.m:510 to fix this issue.

please check.

**Comment by BurrowsWang** [comment]
> This nonnegative value is used only if the delegate doesn’t implement the horizontalTableView:widthForColumnAtIndexPath: method.

@tgarm
